f=open("l.txt","w")
f.write("Hello World1\n")
f.write("Hello World2\n")
f.write("Hello World3\n")
f.close()
f=open("l.txt","r")
line=f.readline()
while line:
    print(line)
    line=f.readline()
